serverctl/urls.py
from django.conf.urls import url

from .views import index
from .views import mypage
from .views import login_view
from .views import signup
from .views import new_server_group
from .views import add_player
from .views import server_group_detail
from .views import player_detail
from .views import start_server
from .views import stop_server


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^mypage/$', mypage, name='mypage'),
    url(r'^login/$', login_view, name='login'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^new_server_group/$', new_server_group, name='new_server_group'),
    url(r'^server_group/(?P<pk>[0-9]+)/$', server_group_detail, name='server_group_detail'),
    url(r'^add_player/$', add_player, name='add_player'),
    url(r'^player_detail/(?P<pk>[0-9]+)/$', player_detail, name='player_detail'),
    url(r'^start_server/(?P<pk>[0-9]+)/$', start_server, name='start_server'),
    url(r'^stop_server/(?P<pk>[0-9]+)/$', stop_server, name='stop_server'),
]

serverctl_prototype/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('serverctl.urls', namespace='serverctl')),
]

serverctl/models.py
from datetime import timedelta
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import uuid
from serverctl import minecraft
from threading import Thread
from serverctl_prototype.utils import slack


class Game(models.Model):
    name = models.CharField('ゲーム名', max_length=32)

    def __str__(self):
        return self.name


class GameServerGroup(models.Model):
    name = models.CharField('ゲームサーバーの名前', max_length=32)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    cost_per_hour = models.PositiveIntegerField('１時間あたりのランニングコスト')

    def save(self, *args, **kwargs):
        super(GameServerGroup, self).save(*args, **kwargs)


class GameServer(models.Model):
    INITIALIZING = 'INITIALIZING'
    LOADING = 'LOADING'
    RUNNING = 'RUNNING'
    SAVING = 'SAVING'
    STOPPING = 'STOPPING'
    STATUS_CHOICES = (
        (INITIALIZING, '準備中'),
        (LOADING, '起動中'),
        (RUNNING, '作動中'),
        (SAVING, '保存中'),
        (STOPPING, '停止中'),
    )
    created_at = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(default=timezone.now)
    once_created = models.BooleanField(default=False)
    group = models.ForeignKey(GameServerGroup, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=12,
        choices=STATUS_CHOICES,
        default=STOPPING,
    )
    ip = models.CharField(max_length=64, default='')
    current_id = models.CharField(max_length=64, default='')

    class Meta:
        get_latest_by = "created_at"

    def _generate_id(self):
        return f'{self.group.game.name}-{str(uuid.uuid4())}'

    def _restart(self):
        slack.send('restart')

        self.started_at = timezone.now()
        self.status = self.LOADING

        prev_id = self.current_id
        self.current_id = self._generate_id()
        self.save()

        minecraft.restart_new_server(prev_id, self.current_id)
        self.ip = minecraft.get_drpolet_ip(self.current_id)
        self.status = self.RUNNING
        self.save()

        slack.send('created')
        slack.send(self.current_id)

    def _start_first(self):
        slack.send('start first')

        self.current_id = self._generate_id()
        self.started_at = timezone.now()
        self.status = self.LOADING
        self.save()

        minecraft.start_new_server(self.current_id)
        self.ip = minecraft.get_drpolet_ip(self.current_id)
        self.status = self.RUNNING
        self.save()

        slack.send('created')
        slack.send(self.current_id)

    def start(self):
        if self.once_created:
            Thread(target=self._restart, daemon=True).start()
            self.once_created = True
            self.save()
        else:
            Thread(target=self._start_first, daemon=True).start()

    def _stop(self):
        last = ServerHistory.objects.filter(server=self, status=self.RUNNING).latest()
        self.status = self.SAVING
        ServerHistory.objects.create(server=self, status=self.SAVING, data_s3_key=last.data_s3_key)
        self.save()

        minecraft.stop(last.data_s3_key)

        self.status = self.STOPPING
        ServerHistory.objects.create(server=self, status=self.STOPPING, data_s3_key=last.data_s3_key)

        players = Player.objects.filter(group=self.group)
        amount = self.calc_payment() // len(players)
        for player in players:
            Payments.objects.create(player=player, group=self.group, amount=amount)
        self.save()

    def stop(self):
        Thread(target=self._stop, daemon=True).start()

    def calc_payment(self):
        hours = (timezone.now() - self.started_at).seconds // 60 // 60 + 1
        return self.group.cost_per_hour * hours

    def save(self, *args, **kwargs):
        super(GameServer, self).save(*args, **kwargs)
        ServerHistory.objects.create(server=self, status=self.status, data_s3_key=self.current_id)

    def __str__(self):
        return self.group.name


class ServerHistory(models.Model):
    server = models.ForeignKey(GameServer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    data_s3_key = models.CharField(max_length=64, default='')
    status = models.CharField(
        max_length=12,
        choices=GameServer.STATUS_CHOICES,
    )

    def __str__(self):
        return f'{self.server}: {self.data_s3_key}'

    def save(self, *args, **kwargs):
        slack.send(self.data_s3_key)
        super(ServerHistory, self).save(*args, **kwargs)

    class Meta:
        get_latest_by = "created_at"


class Player(models.Model):
    OWNER = 'OWNER'
    ADMIN = 'ADMIN'
    NORMAL = 'NORMAL'
    ROLL_CHOICES = (
        (OWNER, '作成者'),
        (ADMIN, '管理者'),
        (NORMAL, '一般'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(GameServerGroup, on_delete=models.CASCADE)
    roll = models.CharField(
        max_length=6,
        choices=ROLL_CHOICES,
        default=NORMAL,
    )


class Payments(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    player = models.ForeignKey(Player)
    group = models.ForeignKey(GameServerGroup)
    amount = models.IntegerField(default=0)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.player.user.username}: {self.amount}円 {self.paid}'

    def save(self, *args, **kwargs):
        super(Payments, self).save(*args, **kwargs)
        if not self.paid:
            type = PaymentHistory.CREATED
        else:
            type = PaymentHistory.PAID
        PaymentHistory.objects.create(payment=self, type=type)


class PaymentHistory(models.Model):
    CREATED = 'CREATED'
    PAID = 'PAID'
    TYPE_CHOICES = (
        (CREATED, '請求'),
        (PAID, '決済'),
    )
    created_at = models.DateTimeField(auto_now_add=True)
    payment = models.ForeignKey(Payments)
    type = models.CharField(
        max_length=12,
        choices=TYPE_CHOICES
    )

serverctl/forms.py
from django import forms

from .models import Game
from .models import GameServer
from .models import GameServerGroup
from .models import Player


class GameServerGroupForm(forms.ModelForm):
    class Meta:
        model = GameServerGroup
        fields = ('name', 'game', 'cost_per_hour')


class AddPlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ('user', 'group', 'roll')
        widgets = {'group': forms.HiddenInput()}

serverctl/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views import View
from django.views.generic.edit import CreateView
from django.views.generic.edit import FormView
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate
from django.contrib.auth import logout
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import GameServer
from .models import GameServerGroup
from .models import Player
from .models import ServerHistory
from .models import Payments

from .forms import GameServerGroupForm
from .forms import AddPlayerForm


@login_required
def index(request):
    servers = GameServerGroup.objects.all()
    return render(request, 'serverctl/index.html', {'servers': servers})


def mypage(request):
    groups = GameServerGroup.objects.filter(player__user=request.user)
    payments = Payments.objects.filter(player__user=request.user)
    context = {
        'groups': groups,
        'payments': payments
    }
    return render(request, 'serverctl/mypage.html', context)


def login_view(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('serverctl:index'))
            return redirect(reverse('serverctl:login'))
    logout(request)
    return render(request, 'serverctl/login.html')


def signup(request):
    print(request.POST)
    if request.method == 'POST':
        user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
        print(user)
        authenticate(username=request.POST['username'], password=request.POST['password'])
        login(request, user)
        return redirect(reverse('serverctl:index'))
    return redirect('/login/')


@login_required
def new_server_group(request):

    if request.method == 'POST':
        game_group = GameServerGroupForm(request.POST)
        group = game_group.save()
        GameServer.objects.create(group=group)
        Player.objects.create(user=request.user, group=group, roll=Player.OWNER)
        return redirect(reverse('serverctl:index'))

    else:
        form = GameServerGroupForm()
        return render(request, 'serverctl/new_server.html', {'form': form})


@login_required
def server_group_detail(request, pk):
    group = GameServerGroup.objects.get(id=pk)
    players = Player.objects.filter(group=group)
    server = GameServer.objects.filter(group=group).latest()
    add_player_form = AddPlayerForm()
    histories = ServerHistory.objects.filter(server=server)
    context = {
        'server_group': group,
        'players': players,
        'server': server,
        'histories': histories,
        'add_player_form': add_player_form
    }
    return render(request, 'serverctl/server_group_detail.html', context)


def add_player(request):
    if request.method == 'POST':
        player = AddPlayerForm(request.POST)
        player = player.save()
        return redirect(f'/server_group/{player.group.pk}/')


def player_detail(request, pk):
    user = Player.objects.get(pk=pk).user
    players = Player.objects.filter(user=user)
    return render(request, 'serverctl/player_detail.html', {'players': players})


def start_server(request, pk):
    server = GameServer.objects.get(pk=pk)
    server.start()
    return redirect(f'/server_group/{server.group.pk}/')


def stop_server(request, pk):
    server = GameServer.objects.get(pk=pk)
    server.stop()
    return redirect(f'/server_group/{server.group.pk}/')

serverctl/templates/serverctl/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap -->
  <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
  {% block css %}{% endblock %}
  {% block js %}{% endblock %}
</head>

<header>
  {% if user.is_authenticated %}
  ようこそ {{ user }} さん <a href="{% url 'serverctl:login' %}">ログアウト</a>
  {% endif %}
</header>

<body>
  <section id="main">
    <div class="layout-main">
      {% block content %}
      {% endblock %}
    </div>
  </section>

  <footer>
    footer
  </footer>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="{% static 'jquery-3.2.0.min.js' %}"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

serverctl/templates/serverctl/index.html
{% extends 'serverctl/base.html' %}

{% block title %}index{% endblock %}

{% block content %}
  <a href="{% url 'serverctl:new_server_group' %}"><h2>新規サーバー作成</h2></a>
  <h2>サーバー一覧</h2>
  <table>
  <thead>
  <tr>
    <td></td>
  </tr>
  </thead>
  {% for server in servers %}
    <li>
      <a href="{% url 'serverctl:server_group_detail' pk=server.id %}">{{ server.name }}</a>
    </li>
  {% endfor %}
  </table>
{% endblock %}

serverctl/templates/serverctl/login.html
{% extends 'serverctl/base.html' %}

{% block title %}index{% endblock %}

{% block content %}
  <h2>ログイン</h2>
  <form action="{% url 'serverctl:login' %}" method="post">
  {% csrf_token %}
  <label for="username">ユーザー名</label>
  <input name="username" id="username" type="text">
  <label for="password">パスワード</label>
  <input name="password" id="password" type="password">
  <button type="submit">ログイン</button>
  </form>

  <h2>新規登録</h2>
  <form action="{% url 'serverctl:signup' %}" method="post">
  {% csrf_token %}
  <label for="username">ユーザー名</label>
  <input name="username" id="username" type="text">
  <label for="password">パスワード</label>
  <input name="password" id="password" type="password">
  <button type="submit">登録</button>
  </form>
{% endblock %}

serverctl/templates/serverctl/mypage.html
{% extends 'serverctl/base.html' %}

{% block title %}index{% endblock %}

{% block content %}
  <h1>マイページ</h1>
  <h2>名前</h2>{{ user.username }}
  <h2>参加サーバー</h2>
  <ul>
  {% for group in groups %}
    <li>
    {{ group.name }}({{ group.game.name }})
    </li>
  {% endfor %}
  </ul>
  <h2>支払い</h2>
  {% for payment in payments %}
    <li>
    {{ payment.group.name }}({{ payment.group.game.name }}) {{ payment.amount }}円
    {% if payment.paid %}
      支払い済み
    {% else %}
      未決済
    {% endif %}
    </li>
  {% endfor %}
{% endblock %}

serverctl/templates/serverctl/new_server.html
{% extends 'serverctl/base.html' %}

{% block title %}index{% endblock %}

{% block content %}

  <form method="post" action="{% url 'serverctl:new_server_group' %}">
  {% csrf_token %}
    {{ form }}
  <button type="submit">作成</button>
  </form>

{% endblock %}

serverctl/templates/serverctl/player_detail.html
{% extends 'serverctl/base.html' %}

{% block title %}index{% endblock %}

{% block content %}
  <h1>プレイヤー詳細</h1>
  <h2>プレイヤー名</h2>
  {% if players %}
   {{ players.1.user.username }}
  {% endif %}

  <h2>参加サーバー</h2>
  {% for player in players %}
    <a href="{% url 'serverctl:server_group_detail' pk=player.group.pk %}">{{ player.group.name }}</a>
    <a href="#">({{ player.group.game.name }})</a><br>
    役割: {{ player.roll }}<br>
  {% endfor %}
{% endblock %}

serverctl/templates/serverctl/server_group_detail.html
{% extends 'serverctl/base.html' %}

{% block title %}index{% endblock %}

{% block content %}
  サーバー詳細
  <h2>サーバー名</h2>
  {{ server_group.name }} ({{ server_group.game.name }})
  <h2>サーバー状態</h2>
  {{ server.get_status_display }}
  {% if server.status == 'STOPPING' %}
    <a href="{% url 'serverctl:start_server' pk=server.pk %}">スタート</a>
  {% elif server.status == 'RUNNING' %}
    <a href="{% url 'serverctl:stop_server' pk=server.pk %}">ストップ</a>
  {% endif %}
  <h2>IP Address</h2>
  {% if server.status == 'RUNNING' %}
    <p>{{ server.ip }}</p>
  {% else %}
    <p>Not Running</p>
  {% endif %}
  <h2>メンバー</h2>
  <ul>
  {% for player in players %}
    <li>
    <a href="{% url 'serverctl:player_detail' pk=player.pk %}">{{ player.user.username }}</a>
    </li>
  {% endfor %}
  </ul>
  <h2>メンバー追加</h2>
  <form action="{% url 'serverctl:add_player' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="group" value="{{ server_group.id }}">
    {{ add_player_form.user }}
    {{ add_player_form.roll }}
  <button type="submit">追加</button>
  </form>
  <h2>履歴</h2>
  <ul>
  {% for history in histories %}
    <li>{{ history.created_at }}: {{ history.get_status_display }}</li>
  {% endfor %}
  </ul>
{% endblock %}